### ISSUE TITLE
Gitlab versioning snippet

### ISSUE THREAD

**Issue by jgsuess** [jgitver/jgitver#103]
Below is 
1. [getting the branch](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)
2. [setting the branch](https://github.com/jgitver/jgitver/issues/40#issuecomment-384531530-permalink)

```
versioning:
  image: openjdk:8-slim
  stage: .pre
  script:
   - export JGITVER_BRANCH=${CI_COMMIT_REF_NAME}
   - java -jar etc/jgitver-0.12.0-executable.jar --useDirty=false > version.txt
  artifacts:
    paths:
    - version.txt
```
