### ISSUE TITLE
Unable to get release build from GitHub Actions.

### ISSUE THREAD

**Issue by Yaytay** [jgitver/jgitver#149]
Hi,

I've been having trouble getting an annotated tag pushed to my GitHub repo to produce a non -SNAPSHOT build.
To test it I've just cloned the https://github.com/jgitver/jgitver-github-actions repo as https://github.com/Yaytay/jgitver-github-actions/, then created an annotated tag and pushed it to GitHub.
The result was a SNAPSHOT version (https://github.com/Yaytay/jgitver-github-actions/runs/6441328564?check_suite_focus=true).

The first time may have been wrong because I pushed the tag twice (because I didn't have Actions enabled in GitHub on the first try) so I did it again: https://github.com/Yaytay/jgitver-github-actions/runs/6441347845?check_suite_focus=true
This time a tag of v2.0.2 led to a jgitver giving a version of v2.0.1!

Using a lightweight tag has the same effect as an annotated tag - tag v2.0.4 created version 2.0.4-SNAPSHOT despite "git describe" saying "v2.0.4".

What do I need to do to get jgitver to work nicely in GitHub Actions?

Thanks

**Comment by McFoggy** [comment]
@Yaytay looking at the git log of your builds it looks like execution occured without the tags
![image](https://user-images.githubusercontent.com/1119660/168846378-f15e070e-d822-4998-902f-1213d40c6daa.png)

update the checkout action parameters so that it extracts tags & enough commits to find the tags.

**Comment by McFoggy** [comment]
Sorry I misunderstood your problem.

Hi, I reproduced on https://github.com/jgitver/jgitver-github-actions

- new commit to add README.md
- tag with lightweight tag v2.1 => 2.1.0-SNAPSHOT as expected
- tag with annotated tag v2.2 => 2.2.0-SNAPSHOT this is not what occurs locally

This need further investigation.

**Comment by Yaytay** [comment]
Hi,
Were you able to dig into this further?
Thanks.

**Comment by pedrolopix** [comment]
I have the same issue and this works for me:

```
steps:
    - uses: actions/checkout@v3
    - name: Checkout
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
```

I noticed that the checkout doesn't retrieve the tags as annotated but as lightweight 
before:
```
     [echo] used version: 0.0.5-SNAPSHOT
     [echo] version calculated: 0.0.5-SNAPSHOT
     [echo] dirty: false
     [echo] head_commit_datetime: Sat Jun 25 16:14:11 2022 +0100
     [echo] git_sha1_8: 4851d347
     [echo] branch_name: 
     [echo] head_tags: 0.0.5
     [echo] head_annotated_tags: 
     [echo] head_lightweight_tags: 0.0.5
     [echo] base_tag: 0.0.5
     [echo] all_tags: 0.0.5
     [echo] all_annotated_tags: 
     [echo] all_lightweight_tags: 0.0.5
     [echo] all_version_tags: 0.0.5
     [echo] all_version_annotated_tags: 
     [echo] all_version_lightweight_tags: 0.0.5
```
after the change:
```
     [echo] used version: 0.0.6
     [echo] version calculated: 0.0.6
     [echo] dirty: false
     [echo] head_commit_datetime: Sat Jun 25 16:59:19 2022 +0100
     [echo] branch_name: 
     [echo] head_tags: 0.0.6
     [echo] head_annotated_tags: 0.0.6
     [echo] head_lightweight_tags: 
     [echo] base_tag: 0.0.6
     [echo] all_tags: 0.0.6,0.0.5
     [echo] all_annotated_tags: 0.0.6,0.0.5
     [echo] all_lightweight_tags: 
     [echo] all_version_tags: 0.0.6,0.0.5
     [echo] all_version_annotated_tags: 0.0.6,0.0.5
     [echo] all_version_lightweight_tags:
```

**Comment by Yaytay** [comment]
Interestingly I've got one project where:
```yaml
    - name: Checkout completely
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
```
is sufficient, and another that needs:
```yaml
    - name: Checkout completely
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout with tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*      
```

I wonder whether we could get something added to actions/checkout to force the full download of tags?

**Comment by McFoggy** [comment]
Did one of you ask the question on the `actions/checkout` project ?

**Comment by Yaytay** [comment]
> Did one of you ask the question on the `actions/checkout` project ?

I haven't.

**Comment by ihostage** [comment]
This problem is related with https://github.com/actions/checkout/issues/882
That why needs manually to do `git fetch --tags --force origin`  to JGitVer works correctly with annotated tags.

**Comment by ihostage** [comment]
My workaround is 
```yaml
- name: Checkout
  uses: actions/checkout@v3
  with:
    # we don't know what commit the last tag was
    fetch-depth: 0
- run: git fetch --tags --force origin # WA: https://github.com/actions/checkout/issues/882
```
